src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column(length: 50)]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    public function getId(): ?int
    {
        return $this->id;
    }
    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\OneToMany(targetEntity: Rating::class, mappedBy: 'user')]
    private $ratings;

    public  bool $isAdmin= false;

    /**
     * @param bool $isAdmin
     */
    public function setIsAdmin(bool $isAdmin): self
    {
        $this->isAdmin = $isAdmin;
        return $this;

    }

    public function getIsAdmin(): bool
    {
        return $this->isAdmin;
    }

    public function __construct()
    {
        $this->ratings = new ArrayCollection();
    }
    public function getRatingScore(){
        return $this->ratings->getRatingScore();
    }
    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
    public function getRoles(): array
    {
        $roles =$this->roles ?? ['ROLE_USER'];
        if ($this->isAdmin) {
            $this->roles = ['ROLE_ADMIN'];
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }


    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return Collection<int, Rating>
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): static
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings->add($rating);
            $rating->setUser($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): static
    {
        if ($this->ratings->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getUser() === $this) {
                $rating->setUser(null);
            }
        }

        return $this;
    }

    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/Customer/Index.html.twig
{% extends "./base.html.twig" %}

{% block body %}
    <div class="movie-page">
        <h3>Customer Page</h3>
        {#        {{ app.user.email }}#}
    </div>

    {#        <a#}
    {#                href="/movies/create"#}
    {#                class="uppercase border border-gray-500 text-lg py-4 px-6 rounded transition transition-all bg-gray-800 text-white hover:bg-white hover:text-gray-800">#}
    {#            Create New movie#}
    {#        </a>#}
{% endblock %}

templates/Customer/movieList.html.twig
{# templates/dashboard/list_movies.html.twig #}
{% block stylesheets %}<link rel="stylesheet" href="{{ asset('css/movies.css') }}">{% endblock %}

{% extends 'base.html.twig' %}

{% block title %}List of Movies{% endblock %}

{% block body %}
        <div class="page-head">
            <h1>Movies List</h1>
        </div>
    <div class="main-content">
        <div class="container">
            {% for movie in movies %}
                <div class="container-item">
                    <div class="card-image">
                        <img class="card-img" src="{{ movie.imagePath }}" alt="Snowy Mountains">
                    </div>
                    <div class="card-content">
                        <h1 class="card-header">{{ movie.title | capitalize }}</h1>
                        <p class="date">release date: {{ movie.releaseDate ? movie.releaseDate|date('Y-m-d') : 'N/A' }}</p>
                        <p class="genre">Genre: {{ movie.genre }}</p>
                        <p class="avg-rating">Average Rating: {{ movie.averageRating }}/10 &#9733;</p>
                        <button class="card-btn">
                            <a href="{{ path('app_movie_view', {'id': movie.id}) }}" class="btn btn-primary">View Details</a>
                        </button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/Customer/movieView.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ movie.getTitle() }}
{% endblock %}
{% block stylesheets %}<link rel="stylesheet" href="{{ asset('css/movieView.css') }}">{% endblock %}

{% block body %}
    <div class="movie-sec">
        <div class="image-sec">
            <img src="{{ movie.getImagePath() }}" alt="{{ movie.getTitle() }}" />
        </div>
        <div class="right-sec">
            <div class="movie-title">
                <h1>{{ movie.getTitle() | capitalize }}</h1>
            </div>
            <div class="detail-sec">
                <p>Release Date: {{ movie.getReleaseDate()|date('F d, Y') }}</p>
                <p>Genre: {{ movie.getGenre() }}</p>
                <p>Description: {{ movie.getDescription() }}</p>
                <p>Category: {{ movie.getCategoryName() }}</p>
            </div>
            <div class="review-sec">
                <h2>Reviews</h2>
                <ul>
                    {% for rating in ratings %}
                        <li>
                            <span class="review-head">
                                <strong>{{ rating.user.getUsername() }}</strong>
                            </span>
                            <span class="review-rating">
                                - {{ rating.ratingScore }} &#9733;
                            </span>
                            <p>{{ rating.review }}</p>
                        </li>
                    {% else %}
                        <li>No reviews available for this movie.</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="rating-form">
                <h2>Rate This Movie</h2>
                <form method="post" action="{{ path('app_movie_rate', {'id': movie.id}) }}">
                    <div id="rating-score">
                        {{ form_row(form.ratingScore) }}
                    </div>
                    <div id="rating-comment">
                        {{ form_row(form.review) }}
                    </div>
                    {{ form_widget(form) }}
                    <div id="rating-btn">
                        <button type="submit">Submit Rating</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}